name: riverpod_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

# 🟢 Configuración de lenguaje
language:
  class-modifiers: true

environment:
  sdk: '>=3.0.0 <4.0.0' # Compatible con Flutter 3.x y null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.1
  random_name_generator: ^1.1.0
  riverpod_annotation: ^2.3.5
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.7.4
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.5

flutter:
  uses-material-design: true
